<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.2 (Python 3.10.0 on win32)" generated="20211111 17:03:58.082" rpa="false" schemaversion="2">
<suite id="s1" name="Robot Interactive Console" source="c:\Users\Neto Rocha\.vscode\extensions\robocorp.robotframework-lsp-0.28.0\src\robotframework_ls\vendored\robotframework_interactive\robot_interactive_console.robot">
<test id="s1-t1" name="Default Task/Test">
<kw name="Interpreter Main Loop" library="MainLoop">
<kw name="Acessar a tela &quot;Controladoria&gt;Caixa&gt;Caixa&gt;Movimentação&gt;Cancelamento de Lançamentos&quot;@nprint @las">
<msg timestamp="20211111 17:03:59.442" level="FAIL">No keyword with name 'Acessar a tela "Controladoria&gt;Caixa&gt;Caixa&gt;Movimentação&gt;Cancelamento de Lançamentos"@nprint @las' found.</msg>
<status status="FAIL" starttime="20211111 17:03:59.442" endtime="20211111 17:03:59.442"/>
</kw>
<kw name="Acessa e Preenche Campo Codigo |CAIXA TESTE SUL|">
<status status="NOT RUN" starttime="20211111 17:03:59.444" endtime="20211111 17:03:59.444"/>
</kw>
<kw name="Seleciona Lote para Cancelar E Preenche Justificativa |ERRO DE LANCAMENTO (REUT.)|">
<status status="NOT RUN" starttime="20211111 17:03:59.446" endtime="20211111 17:03:59.446"/>
</kw>
<status status="PASS" starttime="20211111 17:03:58.129" endtime="20211111 17:04:01.807"/>
</kw>
<status status="PASS" starttime="20211111 17:03:58.128" endtime="20211111 17:04:01.807"/>
</test>
<status status="PASS" starttime="20211111 17:03:58.086" endtime="20211111 17:04:01.808"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="Robot Interactive Console">Robot Interactive Console</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
